#!/usr/bin/env python3
"""
generate_branch_forms.py

Reads data/closure_certificates_v2.json and generates:
  lean/Erdos647BranchForms.lean

This file provides:
  - def branchForms : ℕ → Fin 30 → List BudgetForm  (concrete, replaces opaque)
  - private theorem closed_rN for each of 82 closed residues
  - theorem closed_residue_all_branches (discharges the sorry in ReductionChain)

Key design decisions:
  - branchForms is a concrete match expression, not opaque.
  - For level-0 residues: same form list for all c (c is ignored).
  - For level-1 branched: match on c.val for branch-specific forms.
  - Hard residues and non-survivors: return [].

  - closed_residue_all_branches proof strategy:
    1. Define a concrete Finset `survivingResiduesLiteral` with all 96 values.
    2. Prove r ∈ survivingResiduesLiteral from r ∈ survivingResidues via native_decide.
    3. Prove r ∉ openResidues14 from hhard.
    4. rcases on the literal Finset membership (96 disjuncts of rfl).
    5. For the 14 unresolved residue cases: simp_all (contradiction from hhard).
    6. For the 82 closed residue cases: apply closed_rN.
"""

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(REPO_ROOT, "data", "closure_certificates_v2.json")
OUT_PATH = os.path.join(REPO_ROOT, "lean", "Erdos647BranchForms.lean")

# Computed surviving residues (in ascending order, matching Finset.range M |>.filter survives)
M = 46189
COEFFS = [105, 140, 210, 252, 280, 315, 420, 504, 630, 840, 1260, 2520]
SIEVE_PRIMES = [11, 13, 17, 19]

def survives(r):
    for d in COEFFS:
        for q in SIEVE_PRIMES:
            if (d * r) % q == 1:
                return False
    return True

SURVIVING = [r for r in range(M) if survives(r)]
assert len(SURVIVING) == 96, f"Expected 96, got {len(SURVIVING)}"
OPEN_RESIDUES_14 = {0, 1716, 2431, 4862, 9009, 9867, 16302, 17017, 17160, 21164, 24453, 29315, 31603, 38896}


def form_str(a, b, budget):
    return f"⟨{a}, {b}, {budget}⟩"


def forms_list_str(forms):
    items = [form_str(f["a_red"], f["b_red"], f["budget"]) for f in forms]
    return "[" + ", ".join(items) + "]"


def main():
    with open(JSON_PATH) as f:
        data = json.load(f)

    certs = data["certificates"]

    # Categorize and sort by residue value
    level0_ble1 = []   # (r, cert)
    level0_inadm = []  # (r, cert)
    level1_br = []     # (r, cert)

    for r_str, cert in sorted(certs.items(), key=lambda x: int(x[0])):
        r = int(r_str)
        lvl = cert["level"]
        if lvl == "level0_ble1":
            level0_ble1.append((r, cert))
        elif lvl in ("level0_inadm_b2", "level0_inadm_b23"):
            level0_inadm.append((r, cert))
        elif lvl == "level1_branched":
            level1_br.append((r, cert))
        else:
            print(f"Warning: unknown level {lvl} for r={r}", file=sys.stderr)

    closed_residues = set(
        [r for r, _ in level0_ble1] +
        [r for r, _ in level0_inadm] +
        [r for r, _ in level1_br]
    )
    assert len(closed_residues) == 82, f"Expected 82 closed, got {len(closed_residues)}"
    assert closed_residues | OPEN_RESIDUES_14 == set(SURVIVING), "Mismatch between closed+open and surviving"

    lines = []

    # -------------------------------------------------------------------
    # Header
    # -------------------------------------------------------------------
    lines += [
        "import Erdos647ClosureData",
        "import Erdos647SieveCertificate",
        "",
        "/-!",
        "# Erdős #647 Branch Forms",
        "",
        "Auto-generated by scripts/generate_branch_forms.py.",
        "Provides a concrete definition of `branchForms` and proves",
        "`closed_residue_all_branches` using the v2 closure certificates.",
        "",
        "No sorry.",
        "-/",
        "",
        "namespace Erdos647BranchForms",
        "",
        "open Erdos647B23Closure Erdos647ClosureCerts Erdos647ClosureData",
        "",
    ]

    # -------------------------------------------------------------------
    # Literal Finset of all 96 surviving residues (for proof dispatch)
    # -------------------------------------------------------------------
    surviving_str = ", ".join(str(r) for r in SURVIVING)
    lines += [
        "/-- Literal Finset containing all 96 surviving residues.",
        "    Used to enumerate cases in closed_residue_all_branches. -/",
        f"private def survivingLiteral : Finset ℕ := " + "{" + surviving_str + "}",
        "",
        "/-- Every member of survivingResidues is in survivingLiteral. -/",
        "private theorem mem_survivingLiteral",
        "    (r : ℕ) (hr : r ∈ Erdos647SieveCertificate.survivingResidues) :",
        "    r ∈ survivingLiteral := by",
        "  simp only [Erdos647SieveCertificate.survivingResidues, survivingLiteral] at *",
        "  simp only [Finset.mem_filter, Finset.mem_range] at hr",
        "  simp only [Finset.mem_insert, Finset.mem_singleton]",
        "  -- native_decide handles the finite case analysis",
        "  native_decide",
        "",
    ]
    # Actually native_decide can't prove universally quantified things about r
    # with a hypothesis. Let me use a different approach:
    # After unfolding, we have r < 46189 ∧ survives r = true.
    # We need: r = 0 ∨ r = 55 ∨ ... (96 disjuncts)
    # This is: if r < 46189 and survives r then r ∈ {0, 55, 484, ...}
    # Which is decidable. We can prove: decide (∀ r < 46189, survives r → r ∈ S) = true
    # Actually, the statement to native_decide is:
    # ∀ r : Fin 46189, survives r.val → r.val ∈ survivingLiteral

    # Remove the flawed approach and replace with a working one:
    lines = lines[:-14]

    lines += [
        "/-- Literal Finset containing all 96 surviving residues.",
        "    Proved equal to survivingResidues by native_decide. -/",
        f"private def survivingLiteral : Finset ℕ := " + "{" + surviving_str + "}",
        "",
        "/-- survivingResidues equals the literal Finset. -/",
        "private theorem survivingResidues_eq :",
        "    Erdos647SieveCertificate.survivingResidues = survivingLiteral := by",
        "  native_decide",
        "",
    ]

    # -------------------------------------------------------------------
    # def branchForms
    # -------------------------------------------------------------------
    lines += [
        "/-- Concrete branch forms for each (residue, branch) pair.",
        "    Returns exactly the certificate witness forms for each closed residue.",
        "    For level-0 residues: ignores c (same forms for all 30 branches).",
        "    For level-1 branched residues: dispatches on c.val.",
        "    For unresolved residues and non-survivors: returns [].-/",
        "def branchForms (r : ℕ) (c : Fin 30) : List BudgetForm :=",
        "  match r with",
    ]

    # Level-0 ble1: single form, independent of c
    for r, cert in level0_ble1:
        form = form_str(cert["a_red"], cert["b_red"], cert["budget"])
        lines.append(f"  | {r} => [{form}]")

    # Level-0 inadm: form list, independent of c
    for r, cert in level0_inadm:
        fl = forms_list_str(cert["witness_forms"])
        lines.append(f"  | {r} => {fl}")

    # Level-1 branched: dispatch on c.val
    for r, cert in level1_br:
        lines.append(f"  | {r} => match c.val with")
        branches = cert["branches"]
        for ci in range(30):
            branch = branches[str(ci)]
            mech = branch["mechanism"]
            if mech == "ble1":
                form = form_str(branch["a_red"], branch["b_red"], branch["budget"])
                lines.append(f"    | {ci} => [{form}]")
            else:
                fl = forms_list_str(branch["witness_forms"])
                lines.append(f"    | {ci} => {fl}")
        lines.append(f"    | _ => []")

    lines += [
        "  | _ => []",
        "",
    ]

    # -------------------------------------------------------------------
    # Per-residue closed theorems
    # -------------------------------------------------------------------
    lines += [
        "-- ---------------------------------------------------------------------------",
        "-- Per-residue closed theorems",
        "-- ---------------------------------------------------------------------------",
        "",
        "-- Level-0 budget-le-1: single witness form, same for all c",
    ]

    for r, cert in level0_ble1:
        lines += [
            f"private theorem closed_r{r} :",
            f"    ∀ c : Fin 30, ∀ u, ¬ SatisfiesBudgets (branchForms {r} c) u := by",
            f"  intro c u",
            f"  simp only [branchForms]",
            f"  exact level0_ble1_closed cert_r{r} [cert_r{r}.form] (by simp) u",
            "",
        ]

    lines.append("-- Level-0 inadmissibility: witness forms, same for all c")
    for r, cert in level0_inadm:
        lines += [
            f"private theorem closed_r{r} :",
            f"    ∀ c : Fin 30, ∀ u, ¬ SatisfiesBudgets (branchForms {r} c) u := by",
            f"  intro c u",
            f"  simp only [branchForms]",
            f"  exact level0_inadm_forms_closed cert_r{r} u",
            "",
        ]

    lines.append("-- Level-1 branched: per-branch dispatch via fin_cases")
    for r, cert in level1_br:
        branches = cert["branches"]
        lines += [
            f"private theorem closed_r{r} :",
            f"    ∀ c : Fin 30, ∀ u, ¬ SatisfiesBudgets (branchForms {r} c) u := by",
            f"  intro c u",
            f"  fin_cases c <;> simp only [branchForms]",
        ]
        for ci in range(30):
            branch = branches[str(ci)]
            mech = branch["mechanism"]
            cert_name_c = f"cert_r{r}_c{ci}"
            if mech == "ble1":
                a, b, budget = branch["a_red"], branch["b_red"], branch["budget"]
                form = form_str(a, b, budget)
                # Use branch_cert_closes_self which works on BranchCert directly
                lines.append(f"  · exact branch_cert_closes_self {cert_name_c} u")
            else:
                lines.append(f"  · exact branch_cert_closes_self {cert_name_c} u")
        lines.append("")

    # -------------------------------------------------------------------
    # Main theorem: closed_residue_all_branches
    # -------------------------------------------------------------------
    # Strategy:
    # 1. Rewrite hr using survivingResidues_eq to get r ∈ survivingLiteral
    # 2. survivingLiteral is a literal Finset, so simp unfolds to disjunction
    # 3. rcases on the 96 disjuncts
    # 4. Hard residue cases: contradiction from hhard (simp_all / omega)
    # 5. Closed residue cases: apply closed_rN

    # Build the rcases pattern: 96 "rfl"s
    rcases = " | ".join(["rfl"] * 96)

    lines += [
        "-- ---------------------------------------------------------------------------",
        "-- Main theorem: closed_residue_all_branches",
        "-- ---------------------------------------------------------------------------",
        "",
        "/-- All 82 closed residues have unsatisfiable branch forms.",
        "    Discharges the sorry in Erdos647ReductionChain. -/",
        "theorem closed_residue_all_branches (r : ℕ)",
        "    (hr : r ∈ Erdos647SieveCertificate.survivingResidues)",
        "    (hhard : r ∉ Erdos647ReductionChain.openResidues14) :",
        "    ∀ c : Fin 30, ∀ u, ¬ SatisfiesBudgets (branchForms r c) u := by",
        "  -- Step 1: Convert hr to membership in literal Finset",
        "  rw [survivingResidues_eq] at hr",
        "  -- Step 2: Unfold survivingLiteral to get disjunction r = v₁ ∨ r = v₂ ∨ ...",
        "  simp only [survivingLiteral, Erdos647ReductionChain.openResidues14,",
        "    Finset.mem_insert, Finset.mem_singleton] at hr hhard",
        "  -- Step 3: Case analysis over all 96 surviving residues",
        f"  rcases hr with {rcases}",
    ]

    # Emit one bullet per residue in SURVIVING order
    for r in SURVIVING:
        if r in OPEN_RESIDUES_14:
            lines.append(f"  · simp_all  -- r = {r} is unresolved, contradicts hhard")
        else:
            lines.append(f"  · exact closed_r{r}  -- r = {r} closed")

    lines += [
        "",
        "end Erdos647BranchForms",
        "",
    ]

    output = "\n".join(lines)
    with open(OUT_PATH, "w") as f:
        f.write(output)

    print(f"Written to {OUT_PATH}")
    print(f"Lines: {len(lines)}")
    print(f"  Level-0 ble1:     {len(level0_ble1)}")
    print(f"  Level-0 inadm:    {len(level0_inadm)}")
    print(f"  Level-1 branched: {len(level1_br)}")
    print(f"  Total closed:     {len(closed_residues)}")
    print(f"  Surviving count:  {len(SURVIVING)}")


if __name__ == "__main__":
    main()
