import Mathlib.NumberTheory.ArithmeticFunction.Misc
import Mathlib.Tactic

/-!
# Erdős Problem #647 — top-level orchestrator

Reformulation (Bloom):
  max_{m < n} (m + τ(m)) ≤ n + 2
is equivalent to τ(n-k) ≤ k+2 for every 1 ≤ k < n. Known solution set is
{1,2,3,4,5,6,8,10,12,24}; the open question is whether any n > 24 exists.

This file deliberately bypasses the 93-file `Erdos647*` tree so that
`#print axioms Erdos647Main.erdos647` reveals exactly one open axiom —
the large-N asymptotic gap flagged by Tao on 2026-01-28.

Layer A (finite coverage, 25 ≤ n ≤ 84) is closed by bounded decision.
Layer B (extended modular forcing, n > 84 ⇒ n = 2520N with twelve
almost-prime shape conditions on linear forms dN-1) reduces to 96
residues mod 46189, then to 2 hard residues {0, 24310} by recursive
caveat refactorization.

HISTORICAL NOTE: the docstring above reflects the legacy 92/4
framing. The current reclassification (91/5) refines this to 91 closed
residues plus 5 hard residues {0, 1716, 4862, 16302, 17160}. See
`Erdos647ReductionChain.lean` for the current chain and
`Erdos647ClosureCerts.lean`/`ClosureData.lean`/`BranchForms.lean` for
the 207 certificates. The axiom `candidate_false_large` below is the
legacy wrapper; once Bridges 2 and 3 of the reduction chain are
discharged, it is replaced by `candidate_false_large_via_chain` and
the only remaining axiom is `hard_residues_no_solution` (confined to
the 5 hard residues).
-/

open ArithmeticFunction
open scoped sigma

namespace Erdos647Main

/-- Erdős #647 candidate: `max_{m<n} (m + τ(m)) ≤ n+2`, written with
Mathlib's divisor-count function `σ 0 = τ`. -/
def Candidate (n : ℕ) : Prop := ∀ m, m < n → m + σ 0 m ≤ n + 2

instance decidableCandidate (n : ℕ) : Decidable (Candidate n) :=
  Nat.decidableBallLT n _

/-- **Finite coverage** for `25 ≤ n ≤ 84`. Every such `n` has a witness
`m < n` with `m + τ(m) > n + 2` (record-holders 24, 28, 30, 36, 40, 44,
45, 48, 54, 60, 72, 84 dominate the range). Closed by `native_decide`. -/
theorem candidate_false_finite :
    ∀ n, 25 ≤ n → n ≤ 84 → ¬ Candidate n := by
  intro n h25 h84
  interval_cases n <;> (intro hc; revert hc; native_decide)

/-!
## The asymptotic gap

The remaining obligation is `∀ n > 84, ¬ Candidate n`. The community
attempts through 2026-04-15 are:

* Agbanwa (2026-01-28, Zenodo 18390414): asserts that the "domination
  interval generated by m_k overlaps with that of m_{k+1}" for all
  sufficiently large record-holders m_k of F(m) = m + τ(m). Tao rejected
  this as "unproven, and likely false" on the forum the same day.

* Sayan Dutta (2026-01-18) + Alexeev (2026-01-19): modular forcing shows
  that any n > 84 satisfying Candidate must have n = 2520N with
  2520N - 1, 1260N - 1, 630N - 1, 420N - 1, 315N - 1, 210N - 1, 105N - 1
  each lying in a tightly constrained shape class (prime, prime-square,
  or 2·prime / 4·prime after peeling 2-adic valuations). Alexeev's
  witness n = 604517614941240 (N = 239887942437) shows these constraints
  alone are *not* contradictory — so the gap is strictly analytic, not
  purely congruential.

**Stage-1 formal-core reframe (2026-04-21).** The old Bridge-3 budget
lane has been retired from the active proof path. The top-level theorem
surface is now split into:

* `Erdos647ReductionChain.erdos647_conditional_on_openResiduesStage1`,
  a theorem-grade conditional reduction from the `96` sieve survivors to
  the current open residue set; and
* `Erdos647Stage1Axiom.erdos647_with_stage1_axiom`, a wrapper using the
  single intentional Stage-1 axiom over that open set.

Under the current Stage-1 state, the theorem-grade closure count is `55`
(`42` single-overlap + `13` direct full-value), leaving `41` open residues
defined as the complement inside the `96` survivors. -/

end Erdos647Main
