import Erdos647ClosureCerts

/-!
# Erdős #647 Closure Data

Auto-generated by scripts/generate_lean_certs.py.
314 certificates: 55 Level0BLe1Cert,
19 Level0InadmCert, 240 BranchCert.

No sorry.
-/

namespace Erdos647ClosureData

open Erdos647ClosureCerts Erdos647B23Closure

-- Level-0 budget_le_1 certificates (55)

def cert_r55 : Level0BLe1Cert where
  form := ⟨447678, 533, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r484 : Level0BLe1Cert where
  form := ⟨447678, 4691, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r1342 : Level0BLe1Cert where
  form := ⟨447678, 13007, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r3344 : Level0BLe1Cert where
  form := ⟨447678, 32411, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r4631 : Level0BLe1Cert where
  form := ⟨447678, 44885, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r5775 : Level0BLe1Cert where
  form := ⟨67320, 8417, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r6919 : Level0BLe1Cert where
  form := ⟨447678, 67061, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r7348 : Level0BLe1Cert where
  form := ⟨45045, 7166, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r7777 : Level0BLe1Cert where
  form := ⟨24024, 4045, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r8206 : Level0BLe1Cert where
  form := ⟨25740, 4573, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r8635 : Level0BLe1Cert where
  form := ⟨447678, 83693, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r9493 : Level0BLe1Cert where
  form := ⟨32760, 6733, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r12210 : Level0BLe1Cert where
  form := ⟨447678, 118343, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r14212 : Level0BLe1Cert where
  form := ⟨447678, 137747, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r15070 : Level0BLe1Cert where
  form := ⟨447678, 146063, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r15499 : Level0BLe1Cert where
  form := ⟨447678, 150221, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r15928 : Level0BLe1Cert where
  form := ⟨447678, 154379, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r16643 : Level0BLe1Cert where
  form := ⟨67320, 24257, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r16786 : Level0BLe1Cert where
  form := ⟨447678, 162695, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r19074 : Level0BLe1Cert where
  form := ⟨447678, 184871, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r19503 : Level0BLe1Cert where
  form := ⟨447678, 189029, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r20361 : Level0BLe1Cert where
  form := ⟨447678, 197345, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r22363 : Level0BLe1Cert where
  form := ⟨447678, 216749, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r23221 : Level0BLe1Cert where
  form := ⟨447678, 225065, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r24079 : Level0BLe1Cert where
  form := ⟨447678, 233381, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r24794 : Level0BLe1Cert where
  form := ⟨67320, 36137, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r26367 : Level0BLe1Cert where
  form := ⟨447678, 255557, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r26796 : Level0BLe1Cert where
  form := ⟨447678, 259715, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r26884 : Level0BLe1Cert where
  form := ⟨8008, 4661, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r27225 : Level0BLe1Cert where
  form := ⟨447678, 263873, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r27654 : Level0BLe1Cert where
  form := ⟨447678, 268031, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r30514 : Level0BLe1Cert where
  form := ⟨447678, 295751, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r31229 : Level0BLe1Cert where
  form := ⟨447678, 302681, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r31372 : Level0BLe1Cert where
  form := ⟨447678, 304067, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r32945 : Level0BLe1Cert where
  form := ⟨67320, 48017, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r33319 : Level0BLe1Cert where
  form := ⟨12012, 8665, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r34089 : Level0BLe1Cert where
  form := ⟨447678, 330401, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r34518 : Level0BLe1Cert where
  form := ⟨447678, 334559, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r34947 : Level0BLe1Cert where
  form := ⟨447678, 338717, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r35376 : Level0BLe1Cert where
  form := ⟨447678, 342875, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r38522 : Level0BLe1Cert where
  form := ⟨447678, 373367, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r38665 : Level0BLe1Cert where
  form := ⟨447678, 374753, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r39325 : Level0BLe1Cert where
  form := ⟨45045, 38351, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r39380 : Level0BLe1Cert where
  form := ⟨447678, 381683, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r39754 : Level0BLe1Cert where
  form := ⟨24024, 20677, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r40183 : Level0BLe1Cert where
  form := ⟨25740, 22393, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r40612 : Level0BLe1Cert where
  form := ⟨27720, 24373, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r41096 : Level0BLe1Cert where
  form := ⟨67320, 59897, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r41382 : Level0BLe1Cert where
  form := ⟨447678, 401087, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r41470 : Level0BLe1Cert where
  form := ⟨32760, 29413, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r42240 : Level0BLe1Cert where
  form := ⟨447678, 409403, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r42669 : Level0BLe1Cert where
  form := ⟨447678, 413561, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r43527 : Level0BLe1Cert where
  form := ⟨447678, 421877, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r43813 : Level0BLe1Cert where
  form := ⟨67320, 63857, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

def cert_r45815 : Level0BLe1Cert where
  form := ⟨447678, 444053, 1⟩
  budget_le_1 := by decide
  b_ge_2 := by decide

-- Level-0 inadmissibility certificates (19)

def cert_r1287 : Level0InadmCert where
  forms := [⟨58198140, 1621619, 2⟩, ⟨38798760, 1081079, 2⟩, ⟨29099070, 810809, 2⟩, ⟨19399380, 540539, 2⟩, ⟨14549535, 405404, 2⟩, ⟨9699690, 270269, 2⟩, ⟨489060, 13627, 2⟩, ⟨765765, 21337, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r5291 : Level0InadmCert where
  forms := [⟨58198140, 6666659, 2⟩, ⟨38798760, 4444439, 2⟩, ⟨29099070, 3333329, 2⟩, ⟨19399380, 2222219, 2⟩, ⟨14549535, 1666664, 2⟩, ⟨9699690, 1111109, 2⟩, ⟨855855, 98039, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r6149 : Level0InadmCert where
  forms := [⟨116396280, 15495479, 3⟩, ⟨58198140, 7747739, 2⟩, ⟨38798760, 5165159, 2⟩, ⟨29099070, 3873869, 2⟩, ⟨23279256, 3099095, 3⟩, ⟨19399380, 2582579, 2⟩, ⟨14549535, 1936934, 2⟩, ⟨12932920, 1721719, 3⟩, ⟨11639628, 1549547, 3⟩, ⟨556920, 74141, 3⟩, ⟨9699690, 1291289, 2⟩, ⟨489060, 65107, 2⟩, ⟨6466460, 860859, 3⟩, ⟨5819814, 774773, 3⟩, ⟨4849845, 645644, 3⟩, ⟨204204, 27185, 2⟩, ⟨285285, 37979, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r12155 : Level0InadmCert where
  forms := [⟨58198140, 15315299, 2⟩, ⟨38798760, 10210199, 2⟩, ⟨29099070, 7657649, 2⟩, ⟨19399380, 5105099, 2⟩, ⟨14549535, 3828824, 2⟩, ⟨9699690, 2552549, 2⟩, ⟨765765, 201517, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r12584 : Level0InadmCert where
  forms := [⟨58198140, 15855839, 2⟩, ⟨38798760, 10570559, 2⟩, ⟨29099070, 7927919, 2⟩, ⟨19399380, 5285279, 2⟩, ⟨14549535, 3963959, 2⟩, ⟨9699690, 2642639, 2⟩, ⟨408408, 111269, 2⟩, ⟨855855, 233174, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r13442 : Level0InadmCert where
  forms := [⟨116396280, 33873839, 3⟩, ⟨58198140, 16936919, 2⟩, ⟨38798760, 11291279, 2⟩, ⟨29099070, 8468459, 2⟩, ⟨23279256, 6774767, 3⟩, ⟨19399380, 5645639, 2⟩, ⟨14549535, 4234229, 2⟩, ⟨12932920, 3763759, 3⟩, ⟨11639628, 3387383, 3⟩, ⟨9699690, 2822819, 2⟩, ⟨471240, 137141, 3⟩, ⟨489060, 142327, 2⟩, ⟨6466460, 1881879, 3⟩, ⟨5819814, 1693691, 3⟩, ⟨4849845, 1411409, 3⟩, ⟨285285, 83024, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r19877 : Level0InadmCert where
  forms := [⟨58198140, 25045019, 2⟩, ⟨38798760, 16696679, 2⟩, ⟨29099070, 12522509, 2⟩, ⟨19399380, 8348339, 2⟩, ⟨14549535, 6261254, 2⟩, ⟨9699690, 4174169, 2⟩, ⟨855855, 368309, 2⟩, ⟨170170, 73231, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r20306 : Level0InadmCert where
  forms := [⟨58198140, 25585559, 2⟩, ⟨38798760, 17057039, 2⟩, ⟨29099070, 12792779, 2⟩, ⟨19399380, 8528519, 2⟩, ⟨14549535, 6396389, 2⟩, ⟨9699690, 4264259, 2⟩, ⟨456456, 200671, 2⟩, ⟨765765, 336652, 2⟩, ⟨2145, 943, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r20735 : Level0InadmCert where
  forms := [⟨116396280, 52252199, 3⟩, ⟨58198140, 26126099, 2⟩, ⟨38798760, 17417399, 2⟩, ⟨29099070, 13063049, 2⟩, ⟨23279256, 10450439, 3⟩, ⟨19399380, 8708699, 2⟩, ⟨14549535, 6531524, 2⟩, ⟨12932920, 5805799, 3⟩, ⟨11639628, 5225219, 3⟩, ⟨9699690, 4354349, 2⟩, ⟨489060, 219547, 2⟩, ⟨408408, 183341, 2⟩, ⟨6466460, 2902899, 3⟩, ⟨5819814, 2612609, 3⟩, ⟨4849845, 2177174, 3⟩, ⟨285285, 128069, 3⟩, ⟨85085, 38196, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r27170 : Level0InadmCert where
  forms := [⟨58198140, 34234199, 2⟩, ⟨38798760, 22822799, 2⟩, ⟨29099070, 17117099, 2⟩, ⟨19399380, 11411399, 2⟩, ⟨14549535, 8558549, 2⟩, ⟨9699690, 5705699, 2⟩, ⟨855855, 503444, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r28028 : Level0InadmCert where
  forms := [⟨116396280, 70630559, 3⟩, ⟨58198140, 35315279, 2⟩, ⟨38798760, 23543519, 2⟩, ⟨29099070, 17657639, 2⟩, ⟨23279256, 14126111, 3⟩, ⟨19399380, 11771759, 2⟩, ⟨14549535, 8828819, 2⟩, ⟨12932920, 7847839, 3⟩, ⟨11639628, 7063055, 3⟩, ⟨9699690, 5885879, 2⟩, ⟨489060, 296767, 2⟩, ⟨6466460, 3923919, 3⟩, ⟨5819814, 3531527, 3⟩, ⟨4849845, 2942939, 3⟩, ⟨170170, 103261, 2⟩, ⟨285285, 173114, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r28457 : Level0InadmCert where
  forms := [⟨58198140, 35855819, 2⟩, ⟨38798760, 23903879, 2⟩, ⟨29099070, 17927909, 2⟩, ⟨19399380, 11951939, 2⟩, ⟨14549535, 8963954, 2⟩, ⟨9699690, 5975969, 2⟩, ⟨765765, 471787, 2⟩, ⟨228228, 140611, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r29601 : Level0InadmCert where
  forms := [⟨58198140, 37297259, 2⟩, ⟨38798760, 24864839, 2⟩, ⟨29099070, 18648629, 2⟩, ⟨19399380, 12432419, 2⟩, ⟨875160, 560861, 2⟩, ⟨14549535, 9324314, 2⟩, ⟨9699690, 6216209, 2⟩, ⟨855855, 548489, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r32032 : Level0InadmCert where
  forms := [⟨58198140, 40360319, 2⟩, ⟨38798760, 26906879, 2⟩, ⟨29099070, 20180159, 2⟩, ⟨19399380, 13453439, 2⟩, ⟨14549535, 10090079, 2⟩, ⟨9699690, 6726719, 2⟩, ⟨437580, 303461, 2⟩, ⟨855855, 593534, 2⟩, ⟨10920, 7573, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r32461 : Level0InadmCert where
  forms := [⟨58198140, 40900859, 2⟩, ⟨38798760, 27267239, 2⟩, ⟨29099070, 20450429, 2⟩, ⟨19399380, 13633619, 2⟩, ⟨14549535, 10225214, 2⟩, ⟨9699690, 6816809, 2⟩, ⟨456456, 320791, 2⟩, ⟨45045, 31657, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r35321 : Level0InadmCert where
  forms := [⟨116396280, 89008919, 3⟩, ⟨58198140, 44504459, 2⟩, ⟨38798760, 29669639, 2⟩, ⟨29099070, 22252229, 2⟩, ⟨23279256, 17801783, 3⟩, ⟨19399380, 14834819, 2⟩, ⟨14549535, 11126114, 2⟩, ⟨12932920, 9889879, 3⟩, ⟨11639628, 8900891, 3⟩, ⟨9699690, 7417409, 2⟩, ⟨489060, 373987, 2⟩, ⟨6466460, 4944939, 3⟩, ⟨5819814, 4450445, 3⟩, ⟨4849845, 3708704, 3⟩, ⟨285285, 218159, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r36608 : Level0InadmCert where
  forms := [⟨58198140, 46126079, 2⟩, ⟨38798760, 30750719, 2⟩, ⟨29099070, 23063039, 2⟩, ⟨19399380, 15375359, 2⟩, ⟨14549535, 11531519, 2⟩, ⟨9699690, 7687679, 2⟩, ⟨765765, 606922, 2⟩, ⟨244530, 193807, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r37752 : Level0InadmCert where
  forms := [⟨116396280, 95135039, 3⟩, ⟨58198140, 47567519, 2⟩, ⟨38798760, 31711679, 2⟩, ⟨29099070, 23783759, 2⟩, ⟨23279256, 19027007, 3⟩, ⟨19399380, 15855839, 2⟩, ⟨875160, 715301, 2⟩, ⟨14549535, 11891879, 2⟩, ⟨12932920, 10570559, 3⟩, ⟨11639628, 9513503, 3⟩, ⟨9699690, 7927919, 2⟩, ⟨489060, 399727, 2⟩, ⟨6466460, 5285279, 3⟩, ⟨5819814, 4756751, 3⟩, ⟨4849845, 3963959, 3⟩, ⟨235620, 192581, 3⟩, ⟨136136, 111269, 3⟩, ⟨285285, 233174, 3⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all

def cert_r44187 : Level0InadmCert where
  forms := [⟨58198140, 55675619, 2⟩, ⟨38798760, 37117079, 2⟩, ⟨29099070, 27837809, 2⟩, ⟨19399380, 18558539, 2⟩, ⟨14549535, 13918904, 2⟩, ⟨9699690, 9279269, 2⟩, ⟨855855, 818759, 2⟩, ⟨204204, 195353, 2⟩]
  p := 2
  p_prime := by decide
  covers := coversModPBool_correct _ _ (by native_decide)
  h2 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h3 := by
    intro f hf hb u
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;>
      simp only [BudgetForm.eval] at * <;> omega
  h_budgets := by
    intro f hf
    simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
    rcases hf with h|h|h|h|h|h|h|h <;> subst h <;> simp_all

-- Level-1 branch certificates (240)

def cert_r858_c0 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 43243, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c1 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 7409902, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c2 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 2349547, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c3 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 21959437, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c4 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 18709891, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c5 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 36508972, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c6 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 549443, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c7 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 51058507, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c8 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 933332399, 3⟩, ⟨1745944200, 466666199, 2⟩, ⟨1163962800, 311110799, 2⟩, ⟨872972100, 233333099, 2⟩, ⟨698377680, 186666479, 3⟩, ⟨581981400, 155555399, 2⟩, ⟨436486050, 116666549, 2⟩, ⟨387987600, 103703599, 3⟩, ⟨349188840, 93333239, 3⟩, ⟨290990700, 77777699, 2⟩, ⟨13693680, 3660127, 2⟩, ⟨218243025, 58333274, 3⟩, ⟨64664600, 17283933, 2⟩, ⟨174594420, 46666619, 3⟩, ⟨145495350, 38888849, 3⟩, ⟨12837825, 3431369, 3⟩, ⟨5105100, 1364521, 2⟩, ⟨16166150, 4320983, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r858_c9 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 41989147, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c10 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 23322499, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c11 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 80157577, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c12 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 13989175, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c13 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 94707112, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c14 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 65268403, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c15 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 109256647, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c16 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1462355, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c17 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 123806182, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c18 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2097295199, 3⟩, ⟨1745944200, 1048647599, 2⟩, ⟨1163962800, 699098399, 2⟩, ⟨872972100, 524323799, 2⟩, ⟨698377680, 419459039, 3⟩, ⟨581981400, 349549199, 2⟩, ⟨436486050, 262161899, 2⟩, ⟨387987600, 233032799, 3⟩, ⟨349188840, 209729519, 3⟩, ⟨290990700, 174774599, 2⟩, ⟨13693680, 8224687, 2⟩, ⟨218243025, 131080949, 3⟩, ⟨193993800, 116516399, 3⟩, ⟨174594420, 104864759, 3⟩, ⟨145495350, 87387299, 3⟩, ⟨12837825, 7710644, 3⟩, ⟨5105100, 3066221, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r858_c19 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 88547659, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c20 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 46601755, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c21 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 152905252, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c22 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 25628803, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c23 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 167454787, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c24 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 111826915, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c25 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 182004322, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c26 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 2375267, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c27 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 196553857, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c28 : BranchCert :=
  .ble1 {
    form := ⟨1701700, 1589307, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r858_c29 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 135106171, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c0 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 259459, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c1 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 7680172, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c2 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 239279039, 3⟩, ⟨1745944200, 119639519, 2⟩, ⟨1163962800, 79759679, 2⟩, ⟨872972100, 59819759, 2⟩, ⟨698377680, 47855807, 3⟩, ⟨581981400, 39879839, 2⟩, ⟨436486050, 29909879, 2⟩, ⟨387987600, 26586559, 3⟩, ⟨349188840, 23927903, 3⟩, ⟨18673200, 1279567, 3⟩, ⟨290990700, 19939919, 2⟩, ⟨14137200, 968741, 3⟩, ⟨46558512, 3190387, 2⟩, ⟨218243025, 14954939, 3⟩, ⟨64664600, 4431093, 2⟩, ⟨174594420, 11963951, 3⟩, ⟨145495350, 9969959, 3⟩, ⟨7335900, 502687, 2⟩, ⟨11486475, 787102, 3⟩, ⟨17459442, 1196395, 2⟩, ⟨1521520, 104261, 2⟩, ⟨16166150, 1107773, 3⟩, ⟨7759752, 531731, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c3 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 22229707, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c4 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 472071599, 3⟩, ⟨1745944200, 236035799, 2⟩, ⟨1163962800, 157357199, 2⟩, ⟨872972100, 118017899, 2⟩, ⟨698377680, 94414319, 3⟩, ⟨581981400, 78678599, 2⟩, ⟨436486050, 59008949, 2⟩, ⟨129329200, 17484133, 2⟩, ⟨349188840, 47207159, 3⟩, ⟨18673200, 2524447, 3⟩, ⟨290990700, 39339299, 2⟩, ⟨14137200, 1911221, 3⟩, ⟨218243025, 29504474, 3⟩, ⟨193993800, 26226199, 3⟩, ⟨174594420, 23603579, 3⟩, ⟨145495350, 19669649, 3⟩, ⟨7335900, 991747, 2⟩, ⟨11486475, 1552867, 3⟩, ⟨32332300, 4371033, 2⟩, ⟨4564560, 617087, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c5 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 23538715, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c6 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 14097283, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c7 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 51328777, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c8 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 9376567, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c9 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 65878312, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c10 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 46817971, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c11 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 80427847, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c12 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1403241839, 3⟩, ⟨1745944200, 701620919, 2⟩, ⟨1163962800, 467747279, 2⟩, ⟨872972100, 350810459, 2⟩, ⟨698377680, 280648367, 3⟩, ⟨581981400, 233873639, 2⟩, ⟨436486050, 175405229, 2⟩, ⟨387987600, 155915759, 3⟩, ⟨349188840, 140324183, 3⟩, ⟨18673200, 7503967, 3⟩, ⟨290990700, 116936819, 2⟩, ⟨14137200, 5681141, 3⟩, ⟨46558512, 18709891, 2⟩, ⟨218243025, 87702614, 3⟩, ⟨193993800, 77957879, 3⟩, ⟨174594420, 70162091, 3⟩, ⟨145495350, 58468409, 3⟩, ⟨7335900, 2947987, 2⟩, ⟨11486475, 4615927, 3⟩, ⟨17459442, 7016209, 2⟩, ⟨4564560, 1834303, 3⟩, ⟨7759752, 3118315, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c13 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 94977382, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c14 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1636034399, 3⟩, ⟨1745944200, 818017199, 2⟩, ⟨1163962800, 545344799, 2⟩, ⟨872972100, 409008599, 2⟩, ⟨698377680, 327206879, 3⟩, ⟨581981400, 272672399, 2⟩, ⟨436486050, 204504299, 2⟩, ⟨387987600, 181781599, 3⟩, ⟨349188840, 163603439, 3⟩, ⟨18673200, 8748847, 3⟩, ⟨290990700, 136336199, 2⟩, ⟨14137200, 6623621, 3⟩, ⟨218243025, 102252149, 3⟩, ⟨64664600, 30296933, 2⟩, ⟨174594420, 81801719, 3⟩, ⟨145495350, 68168099, 3⟩, ⟨7335900, 3437047, 2⟩, ⟨11486475, 5381692, 3⟩, ⟨1521520, 712869, 2⟩, ⟨16166150, 7574233, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c15 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 70097227, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c16 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 37376539, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c17 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 124076452, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c18 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 21016195, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c19 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 138625987, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c20 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 93376483, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c21 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 153175522, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c22 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2567204639, 3⟩, ⟨1745944200, 1283602319, 2⟩, ⟨1163962800, 855734879, 2⟩, ⟨872972100, 641801159, 2⟩, ⟨698377680, 513440927, 3⟩, ⟨581981400, 427867439, 2⟩, ⟨436486050, 320900579, 2⟩, ⟨129329200, 95081653, 2⟩, ⟨349188840, 256720463, 3⟩, ⟨18673200, 13728367, 3⟩, ⟨290990700, 213933719, 2⟩, ⟨14137200, 10393541, 3⟩, ⟨46558512, 34229395, 2⟩, ⟨218243025, 160450289, 3⟩, ⟨193993800, 142622479, 3⟩, ⟨174594420, 128360231, 3⟩, ⟨145495350, 106966859, 3⟩, ⟨7335900, 5393287, 2⟩, ⟨11486475, 8444752, 3⟩, ⟨32332300, 23770413, 2⟩, ⟨17459442, 12836023, 2⟩, ⟨4564560, 3355823, 3⟩, ⟨2586584, 1901633, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c23 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 167725057, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c24 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2799997199, 3⟩, ⟨1745944200, 1399998599, 2⟩, ⟨1163962800, 933332399, 2⟩, ⟨872972100, 699999299, 2⟩, ⟨698377680, 559999439, 3⟩, ⟨581981400, 466666199, 2⟩, ⟨436486050, 349999649, 2⟩, ⟨387987600, 311110799, 3⟩, ⟨349188840, 279999719, 3⟩, ⟨18673200, 14973247, 3⟩, ⟨290990700, 233333099, 2⟩, ⟨14137200, 11336021, 3⟩, ⟨218243025, 174999824, 3⟩, ⟨193993800, 155555399, 3⟩, ⟨174594420, 139999859, 3⟩, ⟨145495350, 116666549, 3⟩, ⟨7335900, 5882347, 2⟩, ⟨11486475, 9210517, 3⟩, ⟨4564560, 3660127, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r2574_c25 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 116655739, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c26 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 60655795, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c27 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 196824127, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c28 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 32655823, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r2574_c29 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 211373662, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c0 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 1283782, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c1 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 136936799, 3⟩, ⟨1745944200, 68468399, 2⟩, ⟨1163962800, 45645599, 2⟩, ⟨872972100, 34234199, 2⟩, ⟨698377680, 27387359, 3⟩, ⟨581981400, 22822799, 2⟩, ⟨436486050, 17117099, 2⟩, ⟨129329200, 5071733, 2⟩, ⟨349188840, 13693679, 3⟩, ⟨290990700, 11411399, 2⟩, ⟨13693680, 537007, 2⟩, ⟨218243025, 8558549, 3⟩, ⟨193993800, 7607599, 3⟩, ⟨174594420, 6846839, 3⟩, ⟨145495350, 5705699, 3⟩, ⟨12837825, 503444, 3⟩, ⟨32332300, 1267933, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r8151_c2 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 10133323, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c3 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 7394587, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c4 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 30382852, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c5 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 6025219, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c6 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 44932387, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c7 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 33412579, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c8 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 59481922, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c9 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 837731, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c10 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 74031457, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c11 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1300899599, 3⟩, ⟨1745944200, 650449799, 2⟩, ⟨1163962800, 433633199, 2⟩, ⟨872972100, 325224899, 2⟩, ⟨698377680, 260179919, 3⟩, ⟨581981400, 216816599, 2⟩, ⟨436486050, 162612449, 2⟩, ⟨387987600, 144544399, 3⟩, ⟨349188840, 130089959, 3⟩, ⟨290990700, 108408299, 2⟩, ⟨13693680, 5101567, 2⟩, ⟨218243025, 81306224, 3⟩, ⟨64664600, 24090733, 2⟩, ⟨174594420, 65044979, 3⟩, ⟨145495350, 54204149, 3⟩, ⟨12837825, 4782719, 3⟩, ⟨16166150, 6022683, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r8151_c12 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 56691835, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c13 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 30673843, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c14 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 103130527, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c15 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 17664847, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c16 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 117680062, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c17 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 79971091, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c18 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 132229597, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c19 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1750643, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c20 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 146779132, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c21 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2464862399, 3⟩, ⟨1745944200, 1232431199, 2⟩, ⟨1163962800, 821620799, 2⟩, ⟨872972100, 616215599, 2⟩, ⟨698377680, 492972479, 3⟩, ⟨581981400, 410810399, 2⟩, ⟨436486050, 308107799, 2⟩, ⟨387987600, 273873599, 3⟩, ⟨349188840, 246486239, 3⟩, ⟨290990700, 205405199, 2⟩, ⟨13693680, 9666127, 2⟩, ⟨218243025, 154053899, 3⟩, ⟨193993800, 136936799, 3⟩, ⟨174594420, 123243119, 3⟩, ⟨145495350, 102702599, 3⟩, ⟨12837825, 9061994, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r8151_c22 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 103250347, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c23 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 53953099, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c24 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 175878202, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c25 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 29304475, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c26 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 190427737, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c27 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 126529603, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c28 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 204977272, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r8151_c29 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 2663555, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c0 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 20915, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c1 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 8941432, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c2 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 259459199, 3⟩, ⟨1745944200, 129729599, 2⟩, ⟨1163962800, 86486399, 2⟩, ⟨872972100, 64864799, 2⟩, ⟨698377680, 51891839, 3⟩, ⟨581981400, 43243199, 2⟩, ⟨26254800, 1950821, 2⟩, ⟨436486050, 32432399, 2⟩, ⟨387987600, 28828799, 3⟩, ⟨349188840, 25945919, 3⟩, ⟨290990700, 21621599, 2⟩, ⟨13693680, 1017487, 2⟩, ⟨218243025, 16216199, 3⟩, ⟨193993800, 14414399, 3⟩, ⟨174594420, 12972959, 3⟩, ⟨145495350, 10810799, 3⟩, ⟨7068600, 525221, 3⟩, ⟨12837825, 953894, 3⟩, ⟨4084080, 303461, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r10582_c3 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 15034219, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c4 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 9845035, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c5 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 38040502, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c6 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 7250443, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c7 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 52590037, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c8 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 38313475, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c9 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 67139572, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c10 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 933827, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c11 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 81689107, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c12 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1423421999, 3⟩, ⟨1745944200, 711710999, 2⟩, ⟨1163962800, 474473999, 2⟩, ⟨872972100, 355855499, 2⟩, ⟨698377680, 284684399, 3⟩, ⟨581981400, 237236999, 2⟩, ⟨26254800, 10702421, 2⟩, ⟨436486050, 177927749, 2⟩, ⟨129329200, 52719333, 2⟩, ⟨349188840, 142342199, 3⟩, ⟨290990700, 118618499, 2⟩, ⟨13693680, 5582047, 2⟩, ⟨218243025, 88963874, 3⟩, ⟨193993800, 79078999, 3⟩, ⟨174594420, 71171099, 3⟩, ⟨145495350, 59309249, 3⟩, ⟨7068600, 2881421, 3⟩, ⟨12837825, 5233169, 3⟩, ⟨32332300, 13179833, 2⟩, ⟨4084080, 1664821, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r10582_c13 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 61592731, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c14 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 33124291, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c15 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 110788177, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c16 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 18890071, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c17 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 125337712, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c18 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 84871987, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c19 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 139887247, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c20 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1846739, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c21 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 154436782, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c22 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2587384799, 3⟩, ⟨1745944200, 1293692399, 2⟩, ⟨1163962800, 862461599, 2⟩, ⟨872972100, 646846199, 2⟩, ⟨698377680, 517476959, 3⟩, ⟨581981400, 431230799, 2⟩, ⟨26254800, 19454021, 2⟩, ⟨436486050, 323423099, 2⟩, ⟨387987600, 287487199, 3⟩, ⟨349188840, 258738479, 3⟩, ⟨290990700, 215615399, 2⟩, ⟨13693680, 10146607, 2⟩, ⟨218243025, 161711549, 3⟩, ⟨64664600, 47914533, 2⟩, ⟨174594420, 129369239, 3⟩, ⟨145495350, 107807699, 3⟩, ⟨7068600, 5237621, 3⟩, ⟨12837825, 9512444, 3⟩, ⟨1361360, 1008727, 2⟩, ⟨16166150, 11978633, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r10582_c23 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 108151243, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c24 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 56403547, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c25 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 183535852, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c26 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 30529699, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c27 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 198085387, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c28 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 131430499, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r10582_c29 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 212634922, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c0 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 2049547, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c1 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 117011, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c2 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 16599082, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c3 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 381981599, 3⟩, ⟨1745944200, 190990799, 2⟩, ⟨1163962800, 127327199, 2⟩, ⟨872972100, 95495399, 2⟩, ⟨698377680, 76396319, 3⟩, ⟨581981400, 63663599, 2⟩, ⟨436486050, 47747699, 2⟩, ⟨387987600, 42442399, 3⟩, ⟨349188840, 38198159, 3⟩, ⟨290990700, 31831799, 2⟩, ⟨13127400, 1436021, 2⟩, ⟨13693680, 1497967, 2⟩, ⟨218243025, 23873849, 3⟩, ⟨64664600, 7073733, 2⟩, ⟨174594420, 19099079, 3⟩, ⟨145495350, 15915899, 3⟩, ⟨12837825, 1404344, 3⟩, ⟨16166150, 1768433, 3⟩, ⟨2042040, 223381, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r13013_c4 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 19935115, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c5 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 12295483, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c6 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 45698152, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c7 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 8475667, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c8 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 60247687, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c9 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 43214371, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c10 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 74797222, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c11 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1029923, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c12 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 89346757, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c13 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1545944399, 3⟩, ⟨1745944200, 772972199, 2⟩, ⟨1163962800, 515314799, 2⟩, ⟨872972100, 386486099, 2⟩, ⟨698377680, 309188879, 3⟩, ⟨581981400, 257657399, 2⟩, ⟨436486050, 193243049, 2⟩, ⟨387987600, 171771599, 3⟩, ⟨349188840, 154594439, 3⟩, ⟨290990700, 128828699, 2⟩, ⟨13127400, 5811821, 2⟩, ⟨13693680, 6062527, 2⟩, ⟨218243025, 96621524, 3⟩, ⟨193993800, 85885799, 3⟩, ⟨174594420, 77297219, 3⟩, ⟨145495350, 64414349, 3⟩, ⟨12837825, 5683619, 3⟩, ⟨2042040, 904061, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r13013_c14 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 66493627, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c15 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 35574739, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c16 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 118445827, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c17 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 20115295, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c18 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 132995362, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c19 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 89772883, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c20 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 147544897, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c21 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1942835, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c22 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 162094432, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c23 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2709907199, 3⟩, ⟨1745944200, 1354953599, 2⟩, ⟨1163962800, 903302399, 2⟩, ⟨872972100, 677476799, 2⟩, ⟨698377680, 541981439, 3⟩, ⟨581981400, 451651199, 2⟩, ⟨436486050, 338738399, 2⟩, ⟨129329200, 100366933, 2⟩, ⟨349188840, 270990719, 3⟩, ⟨290990700, 225825599, 2⟩, ⟨13127400, 10187621, 2⟩, ⟨13693680, 10627087, 2⟩, ⟨218243025, 169369199, 3⟩, ⟨193993800, 150550399, 3⟩, ⟨174594420, 135495359, 3⟩, ⟨145495350, 112912799, 3⟩, ⟨12837825, 9962894, 3⟩, ⟨32332300, 25091733, 2⟩, ⟨680680, 528247, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r13013_c24 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 113052139, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c25 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 58853995, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c26 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 191193502, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c27 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 31754923, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c28 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 205743037, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r13013_c29 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 136331395, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c0 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 2950447, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c1 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 163603439, 3⟩, ⟨1745944200, 81801719, 2⟩, ⟨1163962800, 54534479, 2⟩, ⟨872972100, 40900859, 2⟩, ⟨698377680, 32720687, 3⟩, ⟨581981400, 27267239, 2⟩, ⟨26254800, 1230101, 2⟩, ⟨436486050, 20450429, 2⟩, ⟨387987600, 18178159, 3⟩, ⟨349188840, 16360343, 3⟩, ⟨290990700, 13633619, 2⟩, ⟨15800400, 740287, 3⟩, ⟨46558512, 2181379, 2⟩, ⟨218243025, 10225214, 3⟩, ⟨64664600, 3029693, 2⟩, ⟨174594420, 8180171, 3⟩, ⟨145495350, 6816809, 3⟩, ⟨7068600, 331181, 3⟩, ⟨6846840, 320791, 2⟩, ⟨17459442, 818017, 2⟩, ⟨1361360, 63783, 2⟩, ⟨675675, 31657, 3⟩, ⟨16166150, 757423, 3⟩, ⟨7759752, 363563, 3⟩, ⟨262548, 12301, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c2 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 17499982, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c3 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 396395999, 3⟩, ⟨1745944200, 198197999, 2⟩, ⟨1163962800, 132131999, 2⟩, ⟨872972100, 99098999, 2⟩, ⟨698377680, 79279199, 3⟩, ⟨581981400, 66065999, 2⟩, ⟨26254800, 2980421, 2⟩, ⟨436486050, 49549499, 2⟩, ⟨129329200, 14681333, 2⟩, ⟨349188840, 39639599, 3⟩, ⟨290990700, 33032999, 2⟩, ⟨15800400, 1793647, 3⟩, ⟨218243025, 24774749, 3⟩, ⟨193993800, 22021999, 3⟩, ⟨174594420, 19819799, 3⟩, ⟨145495350, 16516499, 3⟩, ⟨7068600, 802421, 3⟩, ⟨6846840, 777247, 2⟩, ⟨32332300, 3670333, 2⟩, ⟨4084080, 463621, 3⟩, ⟨675675, 76702, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c4 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 20511691, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c5 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 12583771, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c6 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 46599052, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c7 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 8619811, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c8 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 61148587, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c9 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 43790947, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c10 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 75698122, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c11 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1327566239, 3⟩, ⟨1745944200, 663783119, 2⟩, ⟨1163962800, 442522079, 2⟩, ⟨872972100, 331891559, 2⟩, ⟨698377680, 265513247, 3⟩, ⟨581981400, 221261039, 2⟩, ⟨26254800, 9981701, 2⟩, ⟨436486050, 165945779, 2⟩, ⟨387987600, 147507359, 3⟩, ⟨349188840, 132756623, 3⟩, ⟨290990700, 110630519, 2⟩, ⟨15800400, 6007087, 3⟩, ⟨46558512, 17700883, 2⟩, ⟨218243025, 82972889, 3⟩, ⟨193993800, 73753679, 3⟩, ⟨174594420, 66378311, 3⟩, ⟨145495350, 55315259, 3⟩, ⟨7068600, 2687381, 3⟩, ⟨6846840, 2603071, 2⟩, ⟨17459442, 6637831, 2⟩, ⟨4084080, 1552709, 3⟩, ⟨675675, 256882, 3⟩, ⟨7759752, 2950147, 3⟩, ⟨262548, 99817, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c12 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 90247657, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c13 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1560358799, 3⟩, ⟨1745944200, 780179399, 2⟩, ⟨1163962800, 520119599, 2⟩, ⟨872972100, 390089699, 2⟩, ⟨698377680, 312071759, 3⟩, ⟨581981400, 260059799, 2⟩, ⟨26254800, 11732021, 2⟩, ⟨436486050, 195044849, 2⟩, ⟨387987600, 173373199, 3⟩, ⟨349188840, 156035879, 3⟩, ⟨290990700, 130029899, 2⟩, ⟨15800400, 7060447, 3⟩, ⟨218243025, 97522424, 3⟩, ⟨64664600, 28895533, 2⟩, ⟨174594420, 78017939, 3⟩, ⟨145495350, 65014949, 3⟩, ⟨7068600, 3158621, 3⟩, ⟨6846840, 3059527, 2⟩, ⟨1361360, 608327, 2⟩, ⟨675675, 301927, 3⟩, ⟨16166150, 7223883, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c14 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 67070203, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c15 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 35863027, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c16 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 119346727, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c17 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 20259439, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c18 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 133896262, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c19 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 90349459, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c20 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 148445797, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c21 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2491529039, 3⟩, ⟨1745944200, 1245764519, 2⟩, ⟨1163962800, 830509679, 2⟩, ⟨872972100, 622882259, 2⟩, ⟨698377680, 498305807, 3⟩, ⟨581981400, 415254839, 2⟩, ⟨26254800, 18733301, 2⟩, ⟨436486050, 311441129, 2⟩, ⟨129329200, 92278853, 2⟩, ⟨349188840, 249152903, 3⟩, ⟨290990700, 207627419, 2⟩, ⟨15800400, 11273887, 3⟩, ⟨46558512, 33220387, 2⟩, ⟨218243025, 155720564, 3⟩, ⟨193993800, 138418279, 3⟩, ⟨174594420, 124576451, 3⟩, ⟨145495350, 103813709, 3⟩, ⟨7068600, 5043581, 3⟩, ⟨6846840, 4885351, 2⟩, ⟨32332300, 23069713, 2⟩, ⟨17459442, 12457645, 2⟩, ⟨4084080, 2914069, 3⟩, ⟨675675, 482107, 3⟩, ⟨2586584, 1845577, 2⟩, ⟨262548, 187333, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c22 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 162995332, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c23 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2724321599, 3⟩, ⟨1745944200, 1362160799, 2⟩, ⟨1163962800, 908107199, 2⟩, ⟨872972100, 681080399, 2⟩, ⟨698377680, 544864319, 3⟩, ⟨581981400, 454053599, 2⟩, ⟨26254800, 20483621, 2⟩, ⟨436486050, 340540199, 2⟩, ⟨387987600, 302702399, 3⟩, ⟨349188840, 272432159, 3⟩, ⟨290990700, 227026799, 2⟩, ⟨15800400, 12327247, 3⟩, ⟨218243025, 170270099, 3⟩, ⟨193993800, 151351199, 3⟩, ⟨174594420, 136216079, 3⟩, ⟨145495350, 113513399, 3⟩, ⟨7068600, 5514821, 3⟩, ⟨6846840, 5341807, 2⟩, ⟨4084080, 3186341, 3⟩, ⟨675675, 527152, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r18733_c24 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 113628715, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c25 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 59142283, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c26 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 192094402, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c27 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 31899067, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c28 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 206643937, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r18733_c29 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 136907971, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c0 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 61261199, 3⟩, ⟨1745944200, 30630599, 2⟩, ⟨1163962800, 20420399, 2⟩, ⟨872972100, 15315299, 2⟩, ⟨698377680, 12252239, 3⟩, ⟨581981400, 10210199, 2⟩, ⟨436486050, 7657649, 2⟩, ⟨129329200, 2268933, 2⟩, ⟨349188840, 6126119, 3⟩, ⟨290990700, 5105099, 2⟩, ⟨14137200, 248021, 3⟩, ⟨218243025, 3828824, 3⟩, ⟨193993800, 3403399, 3⟩, ⟨174594420, 3063059, 3⟩, ⟨145495350, 2552549, 3⟩, ⟨11486475, 201517, 3⟩, ⟨32332300, 567233, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c1 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 7106299, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c2 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 5881075, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c3 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 25653127, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c4 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 5268463, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c5 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 40202662, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c6 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 30385555, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c7 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 54752197, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c8 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 992431439, 3⟩, ⟨1745944200, 496215719, 2⟩, ⟨1163962800, 330810479, 2⟩, ⟨872972100, 248107859, 2⟩, ⟨698377680, 198486287, 3⟩, ⟨581981400, 165405239, 2⟩, ⟨436486050, 124053929, 2⟩, ⟨387987600, 110270159, 3⟩, ⟨349188840, 99243143, 3⟩, ⟨290990700, 82702619, 2⟩, ⟨14137200, 4017941, 3⟩, ⟨46558512, 13232419, 2⟩, ⟨218243025, 62026964, 3⟩, ⟨193993800, 55135079, 3⟩, ⟨174594420, 49621571, 3⟩, ⟨145495350, 41351309, 3⟩, ⟨11486475, 3264577, 3⟩, ⟨17459442, 4962157, 2⟩, ⟨7759752, 2205403, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c9 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 69301732, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c10 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 1225223999, 3⟩, ⟨1745944200, 612611999, 2⟩, ⟨1163962800, 408407999, 2⟩, ⟨872972100, 306305999, 2⟩, ⟨698377680, 245044799, 3⟩, ⟨581981400, 204203999, 2⟩, ⟨436486050, 153152999, 2⟩, ⟨387987600, 136135999, 3⟩, ⟨349188840, 122522399, 3⟩, ⟨290990700, 102101999, 2⟩, ⟨14137200, 4960421, 3⟩, ⟨218243025, 76576499, 3⟩, ⟨64664600, 22689333, 2⟩, ⟨174594420, 61261199, 3⟩, ⟨145495350, 51050999, 3⟩, ⟨11486475, 4030342, 3⟩, ⟨16166150, 5672333, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c11 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 53664811, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c12 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 29160331, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c13 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 98400802, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c14 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 16908091, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c15 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 112950337, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c16 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 76944067, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c17 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 127499872, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c18 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2156394239, 3⟩, ⟨1745944200, 1078197119, 2⟩, ⟨1163962800, 718798079, 2⟩, ⟨872972100, 539098559, 2⟩, ⟨698377680, 431278847, 3⟩, ⟨581981400, 359399039, 2⟩, ⟨436486050, 269549279, 2⟩, ⟨129329200, 79866453, 2⟩, ⟨349188840, 215639423, 3⟩, ⟨290990700, 179699519, 2⟩, ⟨14137200, 8730341, 3⟩, ⟨46558512, 28751923, 2⟩, ⟨218243025, 134774639, 3⟩, ⟨193993800, 119799679, 3⟩, ⟨174594420, 107819711, 3⟩, ⟨145495350, 89849759, 3⟩, ⟨11486475, 7093402, 3⟩, ⟨32332300, 19966613, 2⟩, ⟨17459442, 10781971, 2⟩, ⟨2586584, 1597329, 2⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c19 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 142049407, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c20 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2389186799, 3⟩, ⟨1745944200, 1194593399, 2⟩, ⟨1163962800, 796395599, 2⟩, ⟨872972100, 597296699, 2⟩, ⟨698377680, 477837359, 3⟩, ⟨581981400, 398197799, 2⟩, ⟨436486050, 298648349, 2⟩, ⟨387987600, 265465199, 3⟩, ⟨349188840, 238918679, 3⟩, ⟨290990700, 199098899, 2⟩, ⟨14137200, 9672821, 3⟩, ⟨218243025, 149324174, 3⟩, ⟨193993800, 132732599, 3⟩, ⟨174594420, 119459339, 3⟩, ⟨145495350, 99549449, 3⟩, ⟨11486475, 7859167, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c21 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 100223323, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c22 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 52439587, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c23 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 171148477, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c24 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 28547719, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c25 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 185698012, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c26 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 123502579, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c27 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 200247547, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r24310_c28 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 3320357039, 3⟩, ⟨1745944200, 1660178519, 2⟩, ⟨1163962800, 1106785679, 2⟩, ⟨872972100, 830089259, 2⟩, ⟨698377680, 664071407, 3⟩, ⟨581981400, 553392839, 2⟩, ⟨436486050, 415044629, 2⟩, ⟨387987600, 368928559, 3⟩, ⟨349188840, 332035703, 3⟩, ⟨290990700, 276696419, 2⟩, ⟨14137200, 13442741, 3⟩, ⟨46558512, 44271427, 2⟩, ⟨218243025, 207522314, 3⟩, ⟨64664600, 61488093, 2⟩, ⟨174594420, 166017851, 3⟩, ⟨145495350, 138348209, 3⟩, ⟨11486475, 10922227, 3⟩, ⟨17459442, 16601785, 2⟩, ⟨16166150, 15372023, 3⟩, ⟨7759752, 7378571, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r24310_c29 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 214797082, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c0 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 1268467, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c1 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 11238727, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c2 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 2962159, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c3 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 25788262, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c4 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 21160339, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c5 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 40337797, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c6 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 597491, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c7 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 54887332, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c8 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 994593599, 3⟩, ⟨1745944200, 497296799, 2⟩, ⟨1163962800, 331531199, 2⟩, ⟨872972100, 248648399, 2⟩, ⟨698377680, 198918719, 3⟩, ⟨581981400, 165765599, 2⟩, ⟨436486050, 124324199, 2⟩, ⟨387987600, 110510399, 3⟩, ⟨349188840, 99459359, 3⟩, ⟨16707600, 4758821, 3⟩, ⟨290990700, 82882799, 2⟩, ⟨13693680, 3900367, 2⟩, ⟨218243025, 62162099, 3⟩, ⟨193993800, 55255199, 3⟩, ⟨174594420, 49729679, 3⟩, ⟨145495350, 41441399, 3⟩, ⟨6126120, 1744901, 2⟩, ⟨12837825, 3656594, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r25168_c9 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 44439595, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c10 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 24547723, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c11 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 83986402, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c12 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 14601787, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c13 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 98535937, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c14 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 67718851, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c15 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 113085472, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c16 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 1510403, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c17 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 127635007, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c18 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 2158556399, 3⟩, ⟨1745944200, 1079278199, 2⟩, ⟨1163962800, 719518799, 2⟩, ⟨872972100, 539639099, 2⟩, ⟨698377680, 431711279, 3⟩, ⟨581981400, 359759399, 2⟩, ⟨436486050, 269819549, 2⟩, ⟨129329200, 79946533, 2⟩, ⟨349188840, 215855639, 3⟩, ⟨16707600, 10328021, 3⟩, ⟨290990700, 179879699, 2⟩, ⟨13693680, 8464927, 2⟩, ⟨218243025, 134909774, 3⟩, ⟨193993800, 119919799, 3⟩, ⟨174594420, 107927819, 3⟩, ⟨145495350, 89939849, 3⟩, ⟨6126120, 3786941, 2⟩, ⟨12837825, 7935869, 3⟩, ⟨32332300, 19986633, 2⟩, ⟨425425, 262982, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r25168_c19 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 90998107, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c20 : BranchCert :=
  .ble1 {
    form := ⟨69837768, 47826979, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c21 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 156734077, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c22 : BranchCert :=
  .ble1 {
    form := ⟨34918884, 26241415, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c23 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 171283612, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c24 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 114277363, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c25 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 185833147, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c26 : BranchCert :=
  .ble1 {
    form := ⟨2738736, 2423315, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c27 : BranchCert :=
  .ble1 {
    form := ⟨218243025, 200382682, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }

def cert_r25168_c28 : BranchCert :=
  .inadm {
    forms := [⟨3491888400, 3322519199, 3⟩, ⟨1745944200, 1661259599, 2⟩, ⟨1163962800, 1107506399, 2⟩, ⟨872972100, 830629799, 2⟩, ⟨698377680, 664503839, 3⟩, ⟨581981400, 553753199, 2⟩, ⟨436486050, 415314899, 2⟩, ⟨387987600, 369168799, 3⟩, ⟨349188840, 332251919, 3⟩, ⟨16707600, 15897221, 3⟩, ⟨290990700, 276876599, 2⟩, ⟨13693680, 13029487, 2⟩, ⟨218243025, 207657449, 3⟩, ⟨64664600, 61528133, 2⟩, ⟨174594420, 166125959, 3⟩, ⟨145495350, 138438299, 3⟩, ⟨6126120, 5828981, 2⟩, ⟨12837825, 12215144, 3⟩, ⟨16166150, 15382033, 3⟩, ⟨1276275, 1214371, 3⟩]
    p := 2
    p_prime := by decide
    covers := coversModPBool_correct _ _ (by native_decide)
    h2 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h3 := by
      intro f hf hb u
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;>
        simp only [BudgetForm.eval] at * <;> omega
    h_budgets := by
      intro f hf
      simp only [List.mem_cons, List.mem_nil_iff, or_false] at hf
      rcases hf with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h <;> subst h <;> simp_all
  }

def cert_r25168_c29 : BranchCert :=
  .ble1 {
    form := ⟨139675536, 137556619, 1⟩
    budget_le_1 := by decide
    b_ge_2 := by decide
  }
end Erdos647ClosureData
